name: Dale Erwin Real Estate
favicon: null
layout_spectrum: 0.397233072668314
typography_spectrum: 0.2410659932065755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.39134136703796685
  lightness: 0.6904085881542414
  saturation: 0.004684931365773082
  rhythmicContrast: 0.6505563384853303
purpose: []
